version: '3.8'

services:
  sonar:
    image: sonarqube:latest
    container_name: retro-sonarqube
    ports:
      - "9000:9000"
    environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs